### ISSUE TITLE
large number of "Unknown card in collection: Pool does not contain (Will fetch it from Scryfall)" warnings.

### ISSUE THREAD

**Issue by robertbarrett** [kelesi/mtga-utils#29]
When I run the executable, I get a large output with info messages saying "Unknown card in collection: Pool does not contain
```

C:\Users\robert\Downloads>mtga-export.exe -e pretty_name -f robert.csv
WARNING:root:Could not dynamically generate card sets. Do you have Arena installed?
Info: Unknown card in collection: Pool does not contain 70774 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70775 (Will fetch it from Scryfall)
```

The program eventually does complete succesfully. Is there supposed to be a local db of id's? If I rerun the program against the same player.log file, i get all the same warnings again.

**Comment by kelesi** [comment]
The cards are fetched directly from Arena by python-mtga module. Seems like some Arena update changed something that breaks this. I will try to check this more deeply.

**Comment by kelesi** [comment]
Has been fixed in the lastes Windows executable release.

For Linux you have to install python-mtga from pak21/python-mtga repo until his PR is merged into the original repo (mtgatracker/python-mtga#29).

**Comment by kelesi** [comment]
@robertbarrett Does it work for you now?

**Comment by ElLorans** [comment]
I still face the same issue when using mtga-export.py, but not with the executable. As mtga, I am using your fork:

```
>python mtga-export.py --goldfish -f mtga_collection_goldfish.csv
Found data @
C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Downloads\Data
C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Downloads\Data
WARNING! Could not dynamically generate card sets. Do you have Arena installed?
Info: Unknown card in collection: Pool does not contain 70141 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70267 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70202 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70380 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70163 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70386 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70334 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70275 (Will fetch it from Scryfall)
Info: Unknown card in collection: Pool does not contain 70379 (Will fetch it from Scryfall)
```

**Comment by kelesi** [comment]
The mtga module from PyPi still does not have the fix for some arena
changes. You need to manually install my fork of python-mtga module from my
repo. Please check the README.

Dňa so 22. 8. 2020, 14:39 ElLorans <notifications@github.com> napísal(a):

**Comment by ElLorans** [comment]
I was using your fork. I solved by using the fork from https://github.com/mtgatracker/python-mtga/pull/31/commits/4ed584b573e4123ddf52cca76ad57e48d1c101fc

**Comment by kelesi** [comment]
@ElLorans Sorry, I misread your comment. Yes, you are right. I forgot to mention in the README that you need to install the logging branch from my fork. Master in my fork is identical to master in original repo.
